# Inspired by worfklows in https://github.com/dalek-cryptography/curve25519-dalek/
name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo doc

  build:
    name: Build the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo test

  prove:
    name: Run crux tests and proofs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- run: docker pull ghcr.io/galoisinc/mir-json:2
      #- run: docker run  -v $PWD:/work -w /work  ghcr.io/galoisinc/mir-json:2 -c "cargo crux-test --lib -- -s z3"
      - name: Run ubuntu from dockerhub
        uses: tj-actions/docker-run@v2
        with:
          image: ghcr.io/galoisinc/mir-json:2
          name: mir-json
          options: --mount type=bind,src=$PWD,dst=/work -w /work
          args: |
            -c "pwd; ls -l; cargo --version; cargo crux-test --lib -- -s z3"
