# Inspired by worfklows in https://github.com/dalek-cryptography/curve25519-dalek/
name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo doc

  build:
    name: Build the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo test

  prove:
    name: Run crux tests and proofs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Get latest mir-json
        run: |
          docker pull ghcr.io/galoisinc/mir-json:2
          docker run -v $PWD:/work ghcr.io/galoisinc/mir-json:2 -c "cp -r /home/mir-json/ /work mir-json; /mir-json/rlibs /work/mir-json/rlibs"
      - name: Get stable crux-mir
        run: |
          wget https://github.com/GaloisInc/crucible/releases/download/crux-v0.10/crux-mir-0.10-ubuntu-22.04-X64.tar.gz
          tar -xvf crux-mir-0.10-ubuntu-22.04-X64.tar.gz
      - name: Set env
        run: |
          echo "$PWD/crux-mir-0.10-ubuntu-22.04-X64/bin" >> $GITHUB_PATH
          echo "$PWD/mir-json/.cargo" >> $GITHUB_PATH
          echo "$PWD/mir-json/.rustup" >> $GITHUB_PATH
          echo "CRUX_RUST_LIBRARY_PATH=$PWD/mir-json/rlibs" >> $GITHUB_ENV
      - name: Check env
        run: |
          echo $GITHUB_ENV
          echo $GITHUB_PATH
      - name: Prove
        run: cargo crux-test --lib -- -s z3
