# Inspired by worfklows in https://github.com/dalek-cryptography/curve25519-dalek/
name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo doc

  build:
    name: Build the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default stable
      - run: cargo test

  prove:
    name: Run crux tests and proofs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get the URL for the latest mir-json build
        id: mir-json-build
        run: |
          echo "DOWNLOAD_URL=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.CRUX_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/galoisinc/mir-json/actions/artifacts | jq -r '.artifacts' | jq -c '[ .[] | select ( .name | contains("ubuntu") ) ][0].archive_download_url')" >> $GITHUB_OUTPUT

      - name: Download the latest mir-json build
        run: |
          echo "Downloading from ${{ steps.mir-json-build.outputs.DOWNLOAD_URL }}"
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.CRUX_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" --output mir-json.zip ${{ steps.mir-json-build.outputs.DOWNLOAD_URL }}
          unzip mir-json.zip
          mkdir mir-json-latest
          tar -xf mir-json*.tar.gz --strip-components=1 -C mir-json-latest
          echo "${PWD}/mir-json-latest/bin" >> $GITHUB_PATH
          echo "CRUX_RUST_LIBRARY_PATH=${PWD}/mir-json-latest/rlibs" >> "$GITHUB_ENV"

      - name: Get the URL for the latest Crux-mir build
        id: crux-mir-build
        run: |
          jq --version
          echo "DOWNLOAD_URL=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.CRUX_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/galoisinc/crucible/mir-json/actions/artifacts | jq -r '.artifacts' | jq -c '[ .[] | select ( .name | contains("ubuntu") ) ][0].archive_download_url')" >> $GITHUB_OUTPUT


      - name: Download the latest crux-mir build
        run: |
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.CRUX_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" --output crux-mir.zip ${{ steps.crux-mir-build.outputs.DOWNLOAD_URL }}
          unzip crux-mir.zip
          mkdir crux-mir-latest
          tar -xf crux-mir*.tar.gz --strip-components=1 -C crux-mir-latest
          echo "${PWD}/crux-mir-latest/bin" >> $GITHUB_PATH

      - name: Run proofs
        run: |
          cargo crux-test --lib -- -s z3
